name: flask-app-sap

replicas: 3

configmap:
  configmap_mountpath: /path/to/mountdev1
  configmap_data:
    content: |
      Hello from ConfigMap!
      456
      hhh00
      dev1
    filename: "customdev1.txt"

flask_app:
  port: 8080
  image: tamasujvari/flask-app-sap:latest

service:
  port: 8081

