name: flask-app-sap

replicas: 2

configmap:
  configmap_mountpath: /path/to/mountdev0
  configmap_data:
    content: |
      Hello from ConfigMap!
      123
      hhh88
      dev0
    filename: "customdev0.txt"


flask_app:
  port: 8080
  image: tamasujvari/flask-app-sap:latest

service:
  port: 8081