apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ujvaritamas/sap_hw_conf.git
    targetRevision: HEAD
    path: helm/flask-app-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: myflaskapp-namespace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true #delete old components