apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-dev0
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/ujvaritamas/sap_hw_chart.git
      targetRevision: HEAD
      path: helm/flask-app-chart
      helm:
        valueFiles:
        - $values/values/values_dev0.yaml
    - repoURL: 'https://github.com/ujvaritamas/sap_hw_conf.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: myflaskapp-dev0

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true #delete old components


---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-dev1
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/ujvaritamas/sap_hw_chart.git
      targetRevision: HEAD
      path: helm/flask-app-chart
      helm:
        valueFiles:
        - $values/values/values_dev1.yaml
    - repoURL: 'https://github.com/ujvaritamas/sap_hw_conf.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: myflaskapp-dev1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true #delete old components
