apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}-cont
        image: tamasujvari/flask-app-sap:latest
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
        - name: FILE_PATH
          value: "{{ .Values.configMapMountPath }}/{{ .Values.configMapData.fileName }}" #"/test/exampledir/example.txt"
        volumeMounts:
        - name: config-volume
          mountPath: "{{ .Values.configMapMountPath }}"
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.name }}-configmap