
apiVersion: v1
kind: Service
metadata:
  name: flask-app-sap-service
spec:
  selector:
    app: flask-app-sap
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
